name: 'Mobile App Testing'
description: 'Run tests, linting, and type checking. Expects `yarn tsc`, `yarn test`, and `yarn lint` to be valid commands when they are setup'

inputs:
  GHA_ACCESS_TOKEN:
    description: 'GitHub access token'
    default: ''
    required: false
  GHA_ACCESS_USER:
    description: 'GitHub access user'
    default: ''
    required: false
  JIRA_BASE_URL:
    description: 'The base URL that allows access to the Jira issues'
    default: ''
    required: false
  typescript:
    description: 'If true, run type checking on the app code'
    default: 'true'
    required: false
  changelog:
    description: 'If true, run the changelog checker'
    required: false
  test:
    description: 'If true, run tests'
    default: 'true'
    required: false
  lint:
    description: 'If true, run linting on the source code'
    default: 'true'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Comment on Story Number
      uses: dmsi-io/gha-pull-request@main
      if: inputs.GHA_ACCESS_TOKEN != '' && inputs.GHA_ACCESS_USER != '' && inputs.JIRA_BASE_URL != ''
      with:
        GHA_ACCESS_TOKEN: ${{ inputs.GHA_ACCESS_TOKEN }}
        GHA_ACCESS_USER: ${{ inputs.GHA_ACCESS_USER }}
        JIRA_BASE_URL: ${{ inputs.JIRA_BASE_URL }}
    - name: Node
      id: node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'
    - name: Install
      run: yarn install --frozen-lockfile --prefer-offline
      shell: bash
    - name: Review Code
      uses: dmsi-io/gha-code-review@main
      with:
        changelog: ${{ inputs.changelog }}
        token: ${{ inputs.GHA_ACCESS_TOKEN }}
    - name: ESLint
      if: inputs.lint == 'true'
      run: yarn lint --output-file ./reports/eslint_report.json --format json
      shell: bash
    - name: Annotate Code Linting Results
      uses: ataylorme/eslint-annotate-action@f92355332c64bc5c2d474cc6555edcb1315fdd12
      if: always() && inputs.lint == 'true'
      with:
        repo-token: '${{ github.token }}'
        report-json: './reports/eslint_report.json'
    - name: TypeScript check
      if: inputs.typescript == 'true'
      run: yarn tsc --noEmit
      shell: bash
    - name: Unit Tests
      if: inputs.test == 'true'
      run: yarn test --maxWorkers 4
      shell: bash
